default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jekyll_integration_development

test:
  <<: *default
  database: jekyll_integration_test

production:
  <<: *default
  host: localhost
  pool: 5
  database: jekyll_integration_development
  username: sso
  password: sso